### ISSUE TITLE
Option to consider everything as markdown without needing !doctype

### ISSUE THREAD

**Issue by felixchenier** [clockoon/dokuwiki-plugin-commonmark#11]
Hello and congratulations for this great plugin. I am starting a new wiki and my best solution would be a dokuwiki-style file-based system, but I am so committed to Markdown in other contexts that I really want my wiki to use Markdown on every page.

In that view, I think it would be interesting to have an option in your plugin to preprocess everything without needing a !doctype header. I've been able to achieve it by commenting the `if (preg_match('/\A<!DOCTYPE markdown>/',$event->data))` in action.php, but this is a hack and I'd much prefer having a checkbox at some place to configure the plugin instead.

Is it something that could be envisioned?

Thank you!

**Comment by clockoon** [comment]
Hello.

I have added force_commonmark option, which renders all document as Commonmark without Doctype. ([532432a](https://github.com/clockoon/dokuwiki-plugin-commonmark/commit/532432a23f7b4b82d79cec09140d34f03c26157e)) It have included in next version as well. If any problem exists, please report here.
