### ISSUE TITLE
~~NOTOC~~ not working

### ISSUE THREAD

**Issue by louwers** [clockoon/dokuwiki-plugin-commonmark#15]
This is official [Dokuwiki syntax](https://www.dokuwiki.org/wiki:syntax), and should not be parsed as Markdown.

**Comment by clockoon** [comment]
Disabling TOC works in dokuwiki code block like this:

````
```dokuwiki
~~NOTOC~~
```
````

In normal text, it is parsed as strikethrough, which is intended by Markdown.
