### ISSUE TITLE
Empty lang file may cause an error

### ISSUE THREAD

**Issue by wekev** [clockoon/dokuwiki-plugin-commonmark#21]
Depending of the current PHP-Version and system an empty lang file may cause an error.

Your lang file only contains a "<?php" without any whitespace or more.
In specific installations the js.php request will generate with this a javascript file which contains a "<?phpLANG=" instead of "LANG=".

Could you please remove the empty lang files or extend these to "<?php ?>" or add an comment to these files, which also avoid this bug?

In an old dokumentation of PHP i found this note:
In PHP 5.2 and earlier, the parser does not allow the <?php opening tag to be the only thing in a file. This is allowed as of PHP 5.3 **provided there are one or more whitespace characters after the opening tag**.

Many Thanks!!

**Comment by clockoon** [comment]
Hello.

According to the [forum](https://forum.dokuwiki.org/d/4017-save-space-by-removing-language-files), it could also be possible to remove unused lang file. This change will be included in the next release.
