### ISSUE TITLE
Footnotes are empty

### ISSUE THREAD

**Issue by DivineDominion** [clockoon/dokuwiki-plugin-commonmark#7]
Footnotes render, somewhat at least, but without actual content:

![image](https://user-images.githubusercontent.com/59080/149619461-b9bfd5a2-5c6f-47d7-94fd-1242347ab446.png)
![image](https://user-images.githubusercontent.com/59080/149619462-419b86f1-1ec8-458d-b952-524b033c1350.png)

Tried these reference-style footnotes and also `[^inline footnote text]`, but that also doesn't work.

**Comment by clockoon** [comment]
I have fixed similar issue related to footnote in the latest commit. If it doesn't work for your case, please let me know.

**Comment by DivineDominion** [comment]
Works like a charm now, thank you!
